### ISSUE TITLE
Adding and deleting values dynamically doesn't update slider

### ISSUE THREAD

**Issue by panuchka** [NightCatSama/vue-slider-component#313]
#### Describe the bug

Adding and deleting values dynamically doesn't update the slider. If I have an array of three values, such as years (eg. [2019, 2022, 2026]), the slider does't update if I push items (eg. [2019, 2022, 2026, 2030]) in or pop (eg. [2019, 2022]) them out.

#### Additional context

This can be reproduced going to the example page:
https://nightcatsama.github.io/vue-slider-component/#/basics/simple
By copy pasting this code into the 'Multiple sliders'-example:
```
<template>
  <div>
    <vue-slider v-model="value_2"></vue-slider>
    <vue-slider v-model="value_3"></vue-slider>
    <vue-slider v-model="value_4"></vue-slider>
  </div>
</template>

<script>
  module.exports = {
    components: {
      VueSlider
    },
    data: function () {
      return {
        value_2: [0, 50],
        value_3: [0, 50, 80],
        value_4: [0, 50, 80, 100],
      }
    },
    mounted() {
      setTimeout(() => {
        console.log('popping', this.value_4)
        this.value_4.pop()
        console.log('should have 3 values now', this.value_4)
      }, 5000)
    }
  }
</script>
```

After the timeout, the last item is removed from the array, but the slider doesn't react. This also happens with the insert (sometimes). 

#### Environment 

 - OS & Version: Windows 10
 - Vue version: 2.6.8.
 - Component Version: 3.0.5.

**Comment by NightCatSama** [comment]
Thank you for your feedback, I fixed it in `v3.0.7`.

**Comment by panuchka** [comment]
Thank you for the quick fix! Works now in the example page and in my project. 👍

**Comment by jimut** [comment]
This is still happening in the latest version.
https://codepen.io/jimut/pen/MWgPjyj

**Comment by NightCatSama** [comment]
@jimut Unable to trigger component listener using `push`, you can use the assignment method to modify the `data`.

```js
this.opts.data = this.opts.data.concat([11, 12, 13]);
```

**Comment by Tilesto** [comment]
The same problem. I changed data like: 
`this.sliderData = newData;`
