### ISSUE TITLE
Slider with lazy enabled gets model out of sync with internal state

### ISSUE THREAD

**Issue by zikolach** [NightCatSama/vue-slider-component#375]
If you switch on `lazy` option and move/drag slider relatively quickly releasing mouse button while moving sometimes the value shown on the label is different from one contained in component model (or sent with change event). See screenshot. [Codepen](https://jsfiddle.net/zikolach/zek7y38g/6/) for manual tesing

![Screenshot 2019-06-25 at 14 51 48](https://user-images.githubusercontent.com/79057/60100144-63936b80-9759-11e9-91e3-07dbcbc5366f.png)

**Comment by NightCatSama** [comment]
I have not reappeared, I have been as fast as possible.

Is the value not correct, or the tooltip is not displayed correctly?

**Comment by zikolach** [comment]
The value shown on tooltip is different from one in component model/change event. I think that it is just not updated/propagated outside in some rare cases (appears to be the case 1 of 5-10 times changing upper or lover bound). When it is out of sync - next change of other (correct) bound immediately changes model value to the one displayed on tooltip (makes it synced again).

**Comment by NightCatSama** [comment]
Thanks for the feedback, fixed in version 3.0.33.

**Comment by mixbyme** [comment]
I have the same problem. But I am still experiencing problems.

**Comment by NightCatSama** [comment]
@mixbyme Please provide your parameters and component versions. It is best to have an online example
